name: Notify Discord on PR

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🔔 Новий Pull Request: ${{ github.event.pull_request.title }} від ${{ github.event.pull_request.user.login }}"
